name: timeside
channels:
  - conda-forge
  - thomasfillon
  - soumith
dependencies:
  - aubio  # in conda-forge channel (optionnal)
  - h5py
  - jsonschema
  - jupyter
  - matplotlib
  - mysql-python
  - networkx<2.0
  - numpy
  - pandas
  - pillow
  - python=2.7
  - pyyaml
  - redis
  - scipy
  - simplejson
  - pytables  # named tables in Pypi ...
  - traits
  - yaafe # in yaafe channel (optionnal)
  - Werkzeug
  - yaafe  # in conda-forge channel (optionnal)
  - essentia
  - librosa
  - tensorflow
  - sphinx
  - pytorch
  - torchvision
  - pip:
      - celery==3.*
      - django-bootstrap-pagination
      - django-bootstrap3
      - django-bower
      - django-celery
      - django-cors-headers
      - django-debug-toolbar
      - django-environ
      - django-extensions
      - django==1.9.*
      - djangorestframework==3.6.4
      - jsonfield
      - mutagen
      - py_sonicvisualiser==0.3
      - pympi-ling
      - uwsgi
      - vamp
      - watchdog
      - sphinx_rtd_theme
      - ghp-import
      - jupyterthemes
      - deezer-python
